package com.personal.recipebackend.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "Recipes")
public class Recipe {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String recipeId;

    @DynamoDBAttribute  // Ensure correct mapping
    private String title;

    @DynamoDBAttribute
    private List<String> steps;

    @DynamoDBAttribute
    private String description;

    @DynamoDBAttribute
    private String user_created;
}
